{"name": "test_xfail_unexpected_pass", "status": "passed", "statusDetails": {"message": "XPASS this test is expecting failure"}, "description": "this test is an xfail that will be marked as unexpected success", "start": 1580204610567, "stop": 1580204610567, "uuid": "d25d186e-f207-48f1-a3ae-d28b270c76a4", "historyId": "726669fac8a5bb02e522f8699c456c18", "testCaseId": "ea7f694fc973b2da6c3ef07900bc660e", "fullName": "AllureTestReports#test_xfail_unexpected_pass", "labels": [{"name": "suite", "value": "AllureTestReports"}, {"name": "host", "value": "USBLRNPAVANKUM1"}, {"name": "thread", "value": "16720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AllureTestReports"}]}