{"name": "test_xfail_unexpected_pass", "status": "passed", "statusDetails": {"message": "XPASS this test is expecting failure"}, "description": "this test is an xfail that will be marked as unexpected success", "start": 1580198703224, "stop": 1580198703225, "uuid": "7e88653f-28fb-449d-ad97-99e2fa42274d", "historyId": "726669fac8a5bb02e522f8699c456c18", "testCaseId": "ea7f694fc973b2da6c3ef07900bc660e", "fullName": "AllureTestReports#test_xfail_unexpected_pass", "labels": [{"name": "suite", "value": "AllureTestReports"}, {"name": "host", "value": "USBLRNPAVANKUM1"}, {"name": "thread", "value": "25256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AllureTestReports"}]}