{"name": "test_xfail_unexpected_pass", "status": "passed", "statusDetails": {"message": "XPASS this test is expecting failure"}, "description": "this test is an xfail that will be marked as unexpected success", "start": 1580197504901, "stop": 1580197504902, "uuid": "7eb948ca-de32-475a-8f8c-5f515b92bfa7", "historyId": "726669fac8a5bb02e522f8699c456c18", "testCaseId": "ea7f694fc973b2da6c3ef07900bc660e", "fullName": "AllureTestReports#test_xfail_unexpected_pass", "labels": [{"name": "suite", "value": "AllureTestReports"}, {"name": "host", "value": "USBLRNPAVANKUM1"}, {"name": "thread", "value": "32012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AllureTestReports"}]}