{"name": "test_xfail_unexpected_pass", "status": "passed", "statusDetails": {"message": "XPASS this test is expecting failure"}, "description": "this test is an xfail that will be marked as unexpected success", "start": 1580198442810, "stop": 1580198442810, "uuid": "d8926223-6748-41e7-b6e2-2a35249e777b", "historyId": "726669fac8a5bb02e522f8699c456c18", "testCaseId": "ea7f694fc973b2da6c3ef07900bc660e", "fullName": "AllureTestReports#test_xfail_unexpected_pass", "labels": [{"name": "suite", "value": "AllureTestReports"}, {"name": "host", "value": "USBLRNPAVANKUM1"}, {"name": "thread", "value": "32204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AllureTestReports"}]}