{
  "name": "test_failure",
  "status": "failed",
  "statusDetails": {
    "message": "AssertionError: assert False",
    "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nAllureTestReports.py:11: AssertionError"
  },
  "description": "this test fails",
  "start": 1580197077677,
  "stop": 1580197077677,
  "uuid": "67322f87-4875-482b-81c5-5f97d6180ff0",
  "historyId": "170c955c93af35c300451e8e938abf6b",
  "testCaseId": "f8cc61bce86fd266bb81839d456c4767",
  "fullName": "AllureTestReports#test_failure",
  "labels": [
    {
      "name": "suite",
      "value": "AllureTestReports"
    },
    {
      "name": "host",
      "value": "USBLRNPAVANKUM1"
    },
    {
      "name": "thread",
      "value": "5192-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "AllureTestReports"
    }
  ]
}